spring.datasource.url=jdbc:postgresql://localhost:5432/gymapp
spring.datasource.username=postgres
spring.datasource.password=postgres
api.security.secret=SuperSecretKey123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=validate
logging.level.root=WARN
logging.level.com.manuel.gym_api=INFO
server.error.include-message=never
server.error.include-stacktrace=never
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.endpoints.web.base-path=/actuator