spring.application.name=gym-api

spring.datasource.url=jdbc:postgresql://localhost:5432/gymapp
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jap.hibernate.ddl-auto=update
spring.jap.show-sql=true
spring.jap.properties.hibernate.format_sql=true

api.security.secret=SuperSecretKey123